server:
  port: 8080
spring:
  #  数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: hongjun500
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #缓存
  cache:
    type: redis
  redis:
    timeout: 6000 # 连接超时时长
    host: 127.0.0.1
    port: 6379
    #password: 12345678
    database: 0
    expire:
      #      后台用户过期时间
      common: 60000
    key:
      admin: dianping:admin
      resourceList: dianping:admin:resourceList
    #aop
    aop:
      auto: true
      proxy-target-class: true

  mvc:
    #    favicon:
    #      enabled: off
    # 使用jackson解析
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hello.anmo.dataobject
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: dianping-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /doc.html
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.woff2
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /hello
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false