server:
  port: 8090

spring:
  #  数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: hongjun500
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #缓存
  cache:
    type: redis
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
#    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  aop:
    auto: true
    proxy-target-class: true

  mvc:
    # 使用jackson解析数据
    converters:
      preferred-json-mapper: jackson
    static-path-pattern: /**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #    东八区
    time-zone: GMT+8

  #  静态资源文件映射
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${app-server.upload}

  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: dianping-app-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头



mybatis-plus:
  mapper-locations:
  - classpath:mapping/*.xml
  - classpath:dao/*.xml
  - classpath:oldMapping/*.xml
  type-aliases-package:
  - com.hongjun.dataobject
  - com.hongjun.oldDataobject
  configuration:
      # 开启驼峰
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#阿里云的oss
aliyun:
  oss:
    endpoint:
      fsdfsdom
    accessKeyId:
      Lfdsfds
    accessKeySecret:
      wACaMfsdfsd
    bucketName:
      dianpingfdsfsd
    folderName:
      images
    header:
      http://osfsdfdsfds.com

#白名单路径
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /doc.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.html
      - /**/*.css
      - /**/*.png
      - /**/*.jpg
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
#        放行一些操作无需登录
      - /ums/**
      - /articleInfo/**
      - /posting/listPostInfo
      - /posting/listComment
      - /articleCategory/listArticleCategory
      - /postTopic/listPostTopic
      - /**.json
      - /product/**
      - /shopOrder/**

# 自定义规范redis业务类型key
redis:
  database:
    name: dianping:app
    key:
      otpCode: 'ums:otpCode'
      orderId: 'oms:orderId'
      member: 'ums:member'
      expire:
        otpCode: 600 # 验证码超期时间
        common: 86400 # 24小时

#文件存储在服务器中的路径映射
app-server:
  upload: D:\apache-tomcat-8.5.54\webapps\upload

